### ISSUE TITLE
Question: Forward to multiple servers?

### ISSUE THREAD

**Issue by firrae** [primus/omega-supreme#36]
Hi there,

Quickly going through this I didn't see any mention that this plugin can forward messages to multiple other servers and I'd just like to confirm this is the case? I'm on a project where having a Redis instance isn't as great an option as this idea, but can be done if needed.

Thanks,

Steve

**Comment by lpinca** [comment]
Yes, you can use an array of servers.

**Comment by firrae** [comment]
Awesome, I shall add this to the list of things to work into our R&D phase.

Thanks!
