### ISSUE TITLE
Disconnect specific spark ID on a different instance

### ISSUE THREAD

**Issue by jdelk** [primus/omega-supreme#65]
Is it possible to disconnect a specific spark ID on a different instance using metroplex and omega-supreme?

e.g. you could do this using `primus.spark(id).end()` if the spark was connected to the same instance

**Comment by lpinca** [comment]
You can send that spark a custom message that when received will close it.

**Comment by jdelk** [comment]
That would work, but I'd prefer to enforce this on the server side rather than depending on the client to close the connection.

Is there any other way to do it?

**Comment by lpinca** [comment]
If you want to do it from another server, no there is no other way.
